services:
  db:
    image: postgres:15-alpine
    container_name: pg-dev-db
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: dmarcanalyzer
      POSTGRES_PASSWORD: development_only
      POSTGRES_DB: dmarcanalyzer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dmarcanalyzer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
