services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "25:25"
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://dmarcanalyzer:dmarcanalyzer@db:5432/dmarcanalyzer
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - dmarc-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - dmarc-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dmarcanalyzer
      - POSTGRES_PASSWORD=dmarcanalyzer
      - POSTGRES_DB=dmarcanalyzer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dmarc-network

volumes:
  postgres_data:

networks:
  dmarc-network:
    driver: bridge
